-- MySQL Script generated by MySQL Workbench
-- Tue Aug 30 19:46:54 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bank
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bank
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bank` DEFAULT CHARACTER SET utf8 ;
USE `bank` ;

-- -----------------------------------------------------
-- Table `bank`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`user` (
  `name` VARCHAR(45) NOT NULL,
  `adress` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `profile_categorie` VARCHAR(45) NULL,
  `userid` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`userid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bank`.`TPE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`TPE` (
  `idTPE` INT NOT NULL AUTO_INCREMENT,
  `tpeName` VARCHAR(45) NOT NULL,
  `description` VARCHAR(300) NULL,
  `etat_rep` VARCHAR(45) NOT NULL,
  `TPEuser` INT NULL,
  PRIMARY KEY (`idTPE`),
  INDEX `TPEuser_idx` (`TPEuser` ASC) VISIBLE,
  CONSTRAINT `TPEuser`
    FOREIGN KEY (`TPEuser`)
    REFERENCES `bank`.`user` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
insert into user (name,email,adress,password,profile_categorie) values ("adibbeldi","adibbeldi@gmail.com","beb sadoun 11 avenue paris",12345678,"admin");
insert into user (name,email,adress,password,profile_categorie) values ("azizhssin","azihssin@gmail.com","ibn sina avenue rome",12345678,"user");
insert into TPE(tpeName,description,etat_rep,TPEuser) values('1125',"le pompiste à payé la facture trois fois","en attente",2);
insert into TPE(tpeName,description,etat_rep,TPEuser) values('1126',"le paiement au station total est erroné","en attente",2);
insert into TPE(tpeName,description,etat_rep,TPEuser) values('1127',"erreur du validation de la carte bancaire ","enreparation",2);